### ISSUE TITLE
Look into availability of VT data as a proxy for MA

### ISSUE THREAD

**Issue by mikemahoney218** [codeforboston/clean-slate#101]
[We are attempting to find states with publicly available data in support of our effort to determine how many people are barred from sealing or expunging their records due to multiple offenses](https://github.com/codeforboston/clean-slate/wiki/Data:-The-Big-Picture). While our last attempt to identify a proxy landed on Pennsylvania, we've found mixed evidence about whether or not PA is the best fit as a proxy state for MA -- see [this comment](https://github.com/codeforboston/clean-slate/issues/31#issuecomment-554185094) for more information on that. As such, we're examining several states which may be better fits in order to see if any provide the data we need and are better fits than PA. 

One of the states identified as better fits (see issue #31, PR #52) is Vermont. As such, we should see if we can get sufficient data from Vermont to allow us to approach this problem.

For this state to be a better proxy than PA, it must:

1. Have a digital repository of criminal offense records
1. Contain records of individual offenses (ideally, one record per offense)
1. Have a method to identify offenders and track them across multiple cases
1. Be in a format that we can obtain via web scrapers, without payment or human intervention

The first step of this task will involve identifying the location of criminal offense records online; you'll then need to do some sleuthing to figure out if we're able to hit whatever API serves the records without going through captcha's or paying money. Please update this issue with any progress you make!

**Comment by jeremylang** [comment]
MA data is now available and therefore we no longer have need for a proxy state.
