### ISSUE TITLE
Make sure it is clear to new members where they should write their questions

### ISSUE THREAD

**Issue by niharikasingh** [codeforboston/clean-slate#107]
This is a follow-up from #90. We need to make sure any new users joining the project and reading the onboarding documentation will know: 

1. Where to write down their general-project questions 
2. Where to write down app-team specific questions 
   a. Some of these go in the Google drive doc's called "Designers start here" and "Techies start here" 
   b. Some of these go in the Google form questionnaire
3. Where to write down data-team specific questions

**Comment by jeremylang** [comment]
Samantha was able to find the documentation on her own, though wondered whether it was still active and who answered the questions.

**Comment by jeremylang** [comment]
Decided that we'll use the one document (https://docs.google.com/document/d/1WJGJijM3Fts1RtnKGQSn0tZ82TL4nqU9VRAhhkXyi4Q/edit#) for now to collect new member questions
