### ISSUE TITLE
How do PA crimes in our dataset map to the MA expungable list?

### ISSUE THREAD

**Issue by mikemahoney218** [codeforboston/clean-slate#11]
As we are using the PA detailed dataset as a stand-in for MA crimes, we have to ensure that our PA crimes actually map to the MA crimes that we are interested in. 

A desired endstate for this would be a list of the PA crimes in our dataset with which MA crimes they could map to -- with surprise mappings (or not-mappables) flagged, and distinctions noted between the two.

This is a child issue of https://github.com/codeforboston/clean-slate/issues/6

**Comment by jgarrity** [comment]
This is the list of MA crimes
We only care about which crimes in PA would equal the expungable ones
And if things are close, favor whichever decision would = more expungable crimes
https://docs.google.com/spreadsheets/d/1qs69LbmZD3wURVOH4-8bYZGMnfaM1k2Zp3ONRZV0HMo/edit#gid=579055210

**Comment by jgarrity** [comment]
Pennsylvania XLS list (unknown publishing date) can be found here: http://www.pacourts.us/assets/files/setting-1912/file-1761.xls?cb=214abc

Current official list can be found here as HTML for spot checking/verification: https://www.legis.state.pa.us/cfdocs/legis/LI/consCheck.cfm?txtType=HTM&ttl=18&div=0&chpt=25&sctn=1&subsctn=0

**Comment by jeremylang** [comment]
No longer need a proxy state now that MA data is available.
