### ISSUE TITLE
How can we determine which individuals in the PA dataset have multiple offenses?

### ISSUE THREAD

**Issue by mikemahoney218** [codeforboston/clean-slate#12]
We have a random sample of data (currently ~10% from 2018, but issue #10 hopes to widen that) of PA crimes, which makes it difficult to track which offenders are repeat offenders (and how often, etc etc etc) through the year. While #10 is ongoing and hopes to cast a much broader net, it would be good to spend time thinking about how we can identify repeat offenders if we can't get a more complete dataset.

**Comment by knod** [comment]
Would getting the summary sheets be helpful?

**Comment by dawngraham** [comment]
As a general note, we should try to be thoughtful about the language we use - i.e. using "people who have been convicted / with records in the criminal justice system / etc." instead of "offenders".

**Comment by jeremylang** [comment]
No longer need a proxy state now that MA data is available.
