### ISSUE TITLE
Is Slack down or is it just my luck?

### ISSUE THREAD

**Issue by mikemahoney218** [codeforboston/clean-slate#123]
Hi all -- I can't seem to connect to Slack even a little bit right now! Figured if it's a me thing, this will post in clean-slate-github, and if not, welp. I'll keep trying to get in for a call with the data team!

**Comment by mikemahoney218** [comment]
![Screenshot from 2020-05-12 19-57-36](https://user-images.githubusercontent.com/38229299/81756873-04cb0380-948b-11ea-9247-e13f3d8b1680.png)

@moss @jeremylang 

@srsexton94 & @ whoever else I was meeting with tonight (sorry, didn't catch your name) -- we may need to punt chatting to next week, sorry

**Comment by mikemahoney218** [comment]
https://twitter.com/SlackStatus/status/1260357481244405761?s=20

![Screenshot from 2020-05-12 20-00-37](https://user-images.githubusercontent.com/38229299/81757019-71460280-948b-11ea-9925-5a14b2de209f.png)

at least it's a common issue, lol

**Comment by mikemahoney218** [comment]
cc @berit @niharikasingh

**Comment by niharikasingh** [comment]
It's down for everyone. 

I've set up another meeting room for clean slate people here: 

Join the meeting:
https://meet.jit.si/cleanslatemeeting
To join by phone instead, tap this: +1.512.402.2718,,41905404#
Looking for a different dial-in number?
See meeting dial-in numbers: https://meet.jit.si/static/dialInInfo.html?room=cleanslatemeeting
If also dialing-in through a room phone, join without connecting to audio: https://meet.jit.si/cleanslatemeeting#config.startSilent=true

**Comment by knod** [comment]
@jeremylang

**Comment by mikemahoney218** [comment]
Closing because Slack is back :joy:
