### ISSUE TITLE
Identify data points that can reliably group cases by individual

### ISSUE THREAD

**Issue by srsexton94** [codeforboston/clean-slate#141]
Figure out what in the data can be used to try to identify an individual across multiple cases & assign an ID attribute

**Comment by srsexton94** [comment]
I believe this is complete with Dawn assigning the ID numbers? Used DOB, race, and ethnicity I believe

**Comment by MsPockets** [comment]
The data was filtered by Dawn this weekend and is outlined in the MA_Data.ipynb file, specifically in cell 10. 
We ended up using DOB, Gender, Race, and ethnicity.
