### ISSUE TITLE
Write Scripts to answer the questions from the meeting with Sana

### ISSUE THREAD

**Issue by MsPockets** [codeforboston/clean-slate#154]
Something that we are able to continually work toward no matter the state of the data is writing scripts to answer the questions in #152 

For clarification: The first question and each subsection `a)` of questions 2 and 3 are based on the current law, and subsection `b)` is what the questions would change to if the law changes in the coming months.

**Comment by jeremylang** [comment]
Considering this duplicate of #152 since the work it doesn't seem to need multiple trackers.
