### ISSUE TITLE
How many people are eligible for expungement today?

### ISSUE THREAD

**Issue by mikemahoney218** [codeforboston/clean-slate#21]
The motivation behind the data segment of this project is to answer two questions:

1. _How many people are eligible for expungement today?_ 
2. _What percent will be eligible for expungement if the law changes?_

This is the issue tracking our attempts to answer question 1. 

This is a parent issue for most of the data project; this issue can provide both updates on the state of the data analysis as a whole and also clarify how we view this question moving forward.

**Comment by jeremylang** [comment]
Replaced by #152
