### ISSUE TITLE
What percent of people will be eligible for expungement if the law changes?

### ISSUE THREAD

**Issue by mikemahoney218** [codeforboston/clean-slate#22]
The motivation behind the data segment of this project is to answer two questions:

1. _How many people are eligible for expungement today?_ 
2. _What percent will be eligible for expungement if the law changes?_

This is the issue tracking our attempts to answer question 2. 

This is a parent issue for most of the data project; this issue can provide both updates on the state of the data analysis as a whole and also clarify how we view this question moving forward.

**Comment by mikemahoney218** [comment]
To clarify, "if the law changes" refers to a clear and specific change:

*Multiple offenses should no longer bar someone from expunging their record*.

As it stands right now, people are punished for being unlucky and getting caught being dumb twice. Even ignoring concerns around selective enforcement, this is bad policy, since recidivism is tied to the amount of time it's been since you've committed a crime, and not the number of crimes you've committed. As such, we want to know how many people could be helped by removing this pointless restriction from the law.

Questions that I personally have (and I'll edit this comment as they're resolved)

* Is any second offense enough to bar expungement, or do some not?
* Can two offenses from a single arrest bar someone from expungement?
* Is there another proposed change to the law (from Sana -- we can assume that CJJ has thought about this more than we have) that we want to measure the impact of?

**Comment by jeremylang** [comment]
Replaced by #152
