### ISSUE TITLE
Does our random sample of Pennsylvania data reflect the state’s general data?

### ISSUE THREAD

**Issue by alisonklemencic** [codeforboston/clean-slate#23]
This is a child issue of #6.

**Comment by russmatson** [comment]
I'm sure when we cross reference the data we will realize the limitations but it might be the best
bad idea we have.

**Comment by alisonklemencic** [comment]
We can find some aggregate state crime data for 2008-2018 here: https://crime-data-explorer.fr.cloud.gov/explorer/state/pennsylvania/crime.

**Comment by alisonklemencic** [comment]
Another relevant site for state arrest totals from 2018: https://ucr.fbi.gov/crime-in-the-u.s/2018/crime-in-the-u.s.-2018/tables/table-69.

**Comment by jeremylang** [comment]
No longer need a proxy state now that MA data is available.
