### ISSUE TITLE
Investigate whether there is an identifier in NIBRS for individuals

### ISSUE THREAD

**Issue by alisonklemencic** [codeforboston/clean-slate#26]
No Python/Github required.

**Comment by alisonklemencic** [comment]
Based on this article, NIBRS does not share any personally identifiable information (PII): https://crime-data-explorer.fr.cloud.gov/about.

I can't find any indication that they have an anonymous individual identifier either.

**Comment by cherrymrussell** [comment]
No individual identifier listed in this document, "NIBRS User Manual - Uniform Crime Reporting (UCR) Program": https://ucr.fbi.gov/nibrs/nibrs-user-manual

**Comment by cherrymrussell** [comment]
From https://www.icpsr.umich.edu/icpsrweb/NACJD/NIBRS/concepts.jsp :
> Offender (05) Segment - Offender data include characteristics of each offender (up to 99) involved in a crime incident whether or not an arrest has been made. The object is to capture any information known to law enforcement concerning the offenders even though they may not have been identified.
