### ISSUE TITLE
Code for Boston Demo Day: December 17th

### ISSUE THREAD

**Issue by mikemahoney218** [codeforboston/clean-slate#30]
CfB projects are presenting at demo day on December 17th -- and that's about all we know about that. We need to (a) clarify what demo day is and (b) come up with something to be presenting!

**Comment by mikemahoney218** [comment]
We're thinking we want to explain the why, what, and what next as a part of our presentation, and also work to compliment the app group -- I'll coordinate with their rep.

**Comment by mikemahoney218** [comment]
Audience: people interested in the topics, people interested in getting involved, other CfB folks

**Comment by mikemahoney218** [comment]
roughly 10 minute bits -- 5 minutes of talking, 3 minute Q&A, 2 minutes to change between sets. We could either split time with the app team or be two separate units -- if we split, we could have an extra two minutes at the start to introduce the overall project.

**Comment by dawngraham** [comment]
[Presentation Slides](https://docs.google.com/presentation/d/1vmdBHo8Ner88QeMPq1oOfrEUWBPX1Ujw7dPSto8WHNM/edit?usp=sharing)

[Demo Night Livestream Recording](https://www.youtube.com/watch?v=sVrdJMB8PbI)
