### ISSUE TITLE
Improve folder purpose documentation

### ISSUE THREAD

**Issue by mikemahoney218** [codeforboston/clean-slate#33]
Following issue #29 and a proposal alongside https://docs.google.com/document/d/1VQoCXcJNyfSx7eEVI7U4VrxPHAlIBWnIbJ2gFswa9Rc/edit?usp=sharing , we've reorg'd our repo and plan to move documentation here. However, that documentation doesn't exist here yet. We need to make it!

This issue can be closed once every folder defined in the proposal has a readme describing the why and what of it.

**Comment by knod** [comment]
Just to make the comment in #37 explicit, here's one todo item for that:

* [ ] In analyses/data-expungement/README.md, link to to the documentation about the PA data, questions asked, and conclusions drawn about its proxy status.

**Comment by knod** [comment]
- [ ] Paragraph is confusing in first paragraph of analyses/data-expungement/README.md. [See comment](https://github.com/codeforboston/clean-slate/pull/37/files/cc1a588115f75cd54c1b3ed9c789b979eb27e093#r349200438)

**Comment by knod** [comment]
From @niharikasingh:
- [ ] data/README.md, line 9: Maybe copy the warning about sensitive data not being appropriate for this repo from `scrapers/README.md` to here as well? Just to head off anyone trying to add that data in here. [Original comment](https://github.com/codeforboston/clean-slate/pull/37#discussion_r349391987)
- [ ] data/cleaned/README.md, line 5: Along with source and extent, maybe people should list what script was used to clean this dataset? Then people can form a mental map of `X raw data set + Y cleaning script = Z current clean data set`? [Original comment](https://github.com/codeforboston/clean-slate/pull/37#discussion_r349392606)

**Comment by dawngraham** [comment]
> Just to make the comment in #37 explicit, here's one todo item for that:
> 
> * [ ]  In [In analyses/data-expungement/README.md](https://github.com/codeforboston/clean-slate/pull/37/files#diff-a237cb82739615cf71b2db3fb327e5f1), link to to the documentation about the PA data, questions asked, and conclusions drawn about its proxy status.
> * [ ]  In the data/cleaned, data/processed, and data/dirty READMEs, it might be useful to show a couple of examples, even if they're fake. And then provide an area labeled specifically for the list of data sets with, say, an empty list item.

I created new issues #44 and #45 to address the above comment and made edits to address all others.
