### ISSUE TITLE
Remove .here files if unnecessary

### ISSUE THREAD

**Issue by dawngraham** [codeforboston/clean-slate#43]
@mikemahoney218 
Are the .here files needed in the repo in following locations?:

- [data/cleaned/fbi_aggregated_2018](https://github.com/codeforboston/clean-slate/tree/master/data/cleaned/fbi_aggregated_2018)
- [data/cleaned/fbi_aggregated_data_combined](https://github.com/codeforboston/clean-slate/tree/master/data/cleaned/fbi_aggregated_data_combined)

I'm not as familiar with R - Please go right ahead and comment and close this if the files are required!

**Comment by mikemahoney218** [comment]
Hey Dawn!

R is a bit of a mess when it comes to file paths -- depending on your machine it'll do its _best_ to guess where your relative paths are rooted from, but the process it uses to determine that isn't super portable. I use an extension that looks for the closest .here file to standardize that process across machines. We could just have one .here file in the project's top level and I'll build paths from there, but I didn't want to introduce anything outside of my added folders -- think either way is fine.
