### ISSUE TITLE
Docs bug: Google doc needs permissions to be seen

### ISSUE THREAD

**Issue by knod** [codeforboston/clean-slate#55]
In the first paragraph at https://github.com/codeforboston/clean-slate/wiki, the link of the text 'project overview here' that links to https://docs.google.com/document/d/1RgdgMR6-YVQt7zPbDtKI090_BOEG14Y2LO-jClBC1Kk/edit?usp=sharing is linking to a document that needs permission to be seen.

**Comment by mikemahoney218** [comment]
I don't have access either, it turns out -- hit request, but I wonder if this is related to our meeting notes going missing (did something get deleted somehow?)

**Comment by knod** [comment]
This seems to have been fixed and is in the root folder!
