### ISSUE TITLE
PROPOSAL: Merge all PRs unless those changes actually break something

### ISSUE THREAD

**Issue by knod** [codeforboston/clean-slate#61]
# Why

I've found in other projects that when PRs hang around for a long time:
1. Things get out of sync
2. People lose steam on them and they slow down even more and sometimes die

I think it's especially true in this volunteer work. It's really hard to keep things moving forward at a pace that delivers results.

# How

This is a proposal for the group as a whole, but if the data branch doesn't like it, we'll limit it to the app branch.

We stick to some basic rules that are very lenient about what lets a PR get merged. Other comments and conversations are still welcome/encouraged, they just don't block merging. Improvements can be made after a PR is merged.

## When to Ask for Changes

1. The changes in the code cause a new error.
1. The changes in the code will be pushed to the live app and they expose error that will hurt users.

## When to Merge

1. The documentation in them isn't good enough.
1. The logic could be cleaned up.
1. The formatting isn't pretty.
1. An error was newly found (either related to the PR or not related), but wasn't caused by the changes in the PR.

We can make issues for changes we want to make later to improve the changes. We can also still post comments that reference lines of code inside or outside the PR without blocking the merge.

# Resources

# Proposal History

## 01/20/20
1. **Action:** Proposal made and posted to Slack as a group proposal.

**Comment by niharikasingh** [comment]
Passed with 2 abstains, 2 4s, and 3 5s (@niharikasingh, @berit, @knod).
