### ISSUE TITLE
Transfer Trello board Pending Column issues to Github project

### ISSUE THREAD

**Issue by John-Cassidy** [codeforboston/clean-slate#63]
Trello board - https://trello.com/c/aEYhNWuf/96-transfer-trello-cards-to-github-project

**Comment by John-Cassidy** [comment]
John C transferred all trello items into Github for columns
 - New Agenda
 - To do
Nathan transferred all trello items into Github for columns:
 - Pending

NOTE: we did not transfer any items from the Done column

**Comment by John-Cassidy** [comment]
**Block** - Cannot assign people from Trello because not all people on Github.
[Trello Board](https://trello.com/b/NAslFElb/clean-slate)
[Github Board](https://github.com/codeforboston/clean-slate/projects/2)

**Comment by niharikasingh** [comment]
Items that were completed before we switched to using Github project boards are in the Done column of the Trello project board.
