### ISSUE TITLE
Documentation that still needs to be created

### ISSUE THREAD

**Issue by knod** [codeforboston/clean-slate#65]
## Documentation to create

_When creating a document, link to it in this issue so that we don't duplicate work._

1. App: general intro (as opposed to design and tech/code notes) ([in this folder](https://drive.google.com/drive/u/0/folders/1BGsqYmQk7zmEF9bCvvUuwNC_AtX3t6lJ))
1. Wiki page: What accounts users need to create and how to get familiar with those services on the devices they will be using
   1. (group) Slack
   1. (group) Github (including some markdown)
   1. (group) Google drive (for now)
   1. (app) Plectica
   1. (app tech) Docassemble
1. Orientation script
1. Onboarding script (outlines in meeting checklist page)
1. Weekly/monthly upkeep that needs to happen outside of meeting
1. [Previous proposals and decisions (as issues)](https://github.com/codeforboston/clean-slate/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aproposal)
1. Template for informal decisions
1. (app) Style guide
1. Template for other ~issue types~ general issues (done, unlinkable)
1. Template for formal proposals (done, unlinkable)
1. [Full meeting checklist](https://github.com/codeforboston/clean-slate/wiki/Weekly-Meeting-Checklist) ~(how? printed on paper?)~ in wiki

There's also notes about existing documentation that needs to be considered and possibly incorporated. That's probably for another time.

**Comment by knod** [comment]
Link to a document after creating it.

**Comment by knod** [comment]
App docs should be made on the google drive.

**Comment by knod** [comment]
@berit:
- Item 6: (issue #89 )
- Item 7: decision template

@knod:
- Item 4: onboarding script
- Item 5: Inter-meeting todos. (ex: running test on wiki for links, etc.)

@caitlincoffey:
- Item 3: Orientation script
- Item 1: App intro ([in this folder](https://drive.google.com/drive/u/0/folders/1BGsqYmQk7zmEF9bCvvUuwNC_AtX3t6lJ))

**Comment by knod** [comment]
Each should make issues for each of their items.

**Comment by knod** [comment]
@jeremylang will review #106, onboarding script.

**Comment by jeremylang** [comment]
Split off the remaining items into their own issues. Closing this as it no longer has a status of its own and can still be referenced by the other issues.
