### ISSUE TITLE
Update StakeHolder Google Sheet

### ISSUE THREAD

**Issue by John-Cassidy** [codeforboston/clean-slate#67]
Cory suggested updating this document.

Please coordinate with @Moss and @Neha

[Google Stakeholder Sheet](https://drive.google.com/open?id=14KdhXe-1N5Qy3Y3gNYKeUIrXy1It2wqLiTtD6gn5MLI)

**Comment by niharikasingh** [comment]
Blocked on Cory's input, which we're waiting to receive.

**Comment by jeremylang** [comment]
Word is the value is no longer there. Re-open if that changes.
