### ISSUE TITLE
DECISION: Use this template for proposals

### ISSUE THREAD

**Issue by berit** [codeforboston/clean-slate#68]
# Why

Since we will be using github issues for proposals, an issue template will make it easier to create proposals with all the necessary information.

# How

This proposal was created with the template https://github.com/codeforboston/clean-slate/blob/master/.github/ISSUE_TEMPLATE/proposal-template.md. If folks think this format looks good, we can continue using it, otherwise we can tweak the template as needed.

## Questions:
* Would it be helpful to include our fist-to-five cheat sheet on proposals?
* Or maybe a link to our decision-making documents?

# Resources

* Here is the template: https://github.com/codeforboston/clean-slate/blob/master/.github/ISSUE_TEMPLATE/proposal-template.md
* Our decision-making wiki page: https://github.com/codeforboston/clean-slate/wiki/Making-Decisions

# Proposal History

See how it passed below. We might remove this history stuff since we have comments.

## 2020/01/04
1. Proposal issue made with 'proposal' label and other relevant labels. Was posted to slack (with end date, voting chart, and link to this issue), and post was pinned to the channel.

**Comment by berit** [comment]
Where do we want discussion to happen? Slack or GitHub?

**Comment by knod** [comment]
Small/quick back and forth in slack with more full discussions in here?

**Comment by knod** [comment]
One question - do we want this to be one single proposal template for any proposal or do we want to create three of these - one for the group, one for the data team, and one for the app team? So that things get labeled correctly.

**Comment by knod** [comment]
Also, though we can't auto add these to project boards, isn't there some kind of automation that we can do with labels and project boards? We might be able to use that.

**Comment by knod** [comment]
This passed. 5: @persimmonplatypus , @niharikasingh , and another who needs to be added as a collaborator.
