### ISSUE TITLE
Edit fist-to-five docs to make it based on github proposals

### ISSUE THREAD

**Issue by knod** [codeforboston/clean-slate#69]
Edit fist-to-five docs to make it based on github proposals, not google docs. The language is in the google doc. proposal (that was before the decision): https://docs.google.com/document/d/1DrwZtlrx_lD2hzMJtVZTm1ndCRk8hvQDlRJGanTRMnk/edit?usp=sharing

**Comment by knod** [comment]
Is there a github issue of the proposal doc? All our proposals and decisions need to be issues now (or so we decided). Have we made an issue for that? Maybe it was on the Trello.

**Comment by berit** [comment]
@knod  I created #95 and changed references to google docs to be github issues, is that all that's needed for this task?

**Comment by knod** [comment]
It's looking great! Add info about adding an 'app' or 'data' label, and a 'proposal' label.
