### ISSUE TITLE
Is the Court of Common Pleas a valid proxy for all PA crime?

### ISSUE THREAD

**Issue by mikemahoney218** [codeforboston/clean-slate#7]
Our entire PA crime dataset refers to crimes heard in the Court of Common Pleas. If we are to use this dataset to make generalizations about MA crimes, we need to know what subset of crimes are heard in this court, how they map to total PA crimes, and if they are a valid proxy for all MA crimes. 

Action items here might include research into the PA legal system to determine what crimes are heard in this court, as well as comparison of our dataset to FBI data to see if they map to PA crime rates as well.

This task is a child of https://github.com/codeforboston/clean-slate/issues/6

**Comment by knod** [comment]
We probably have a way to access magisterial court dockests as well (though not summaries), which is the other kind that we know of.

**Comment by knod** [comment]
Update: The only other data we've been able to access so far is the magisterial traffic court data.

**Comment by jeremylang** [comment]
No longer need a proxy state now that MA data is available.
