### ISSUE TITLE
Add "how to delete a file from docassemble/playground" instructions to app wiki

### ISSUE THREAD

**Issue by knod** [codeforboston/clean-slate#73]
The instructions are in meeting notes from a few weeks ago, and also in slack.

**Comment by knod** [comment]
Copied from https://github.com/knod/docassemble-juvenilesealing/issues/54.

**Comment by knod** [comment]
We weren't sure about this step, @niharikasingh:

Push all your changes.

Did that step end up being needed? Did it create new changes that had to be merged in?

**Comment by knod** [comment]
Added to the https://github.com/codeforboston/clean-slate/wiki/Contributing-to-App-Code page, but will wait to close this item till the question gets answered.

**Comment by niharikasingh** [comment]
Closed thru instructions here https://github.com/codeforboston/clean-slate/wiki/Contributing-to-App-Code#deleting-files-harder-than-you-think

**Comment by knod** [comment]
Closes https://github.com/knod/docassemble-juvenilesealing/issues/54 too.
