### ISSUE TITLE
Move app style guide from wiki to google drive

### ISSUE THREAD

**Issue by knod** [codeforboston/clean-slate#78]
https://github.com/codeforboston/clean-slate/wiki/App-Style-Guide

**Comment by srsexton94** [comment]
This one doesn't seem to have super substantial content - I summarized to a line and added it to the [style section](https://docs.google.com/document/d/1Up_4XqU7BPIQT6_ThCYJQeD63SpdhI0ZELyC01mgw3o/edit#bookmark=id.86yvyhn1jkvp)

If that's not sufficient I'm happy to reopen
