### ISSUE TITLE
Move app code contribution guidelines from wiki to google drive

### ISSUE THREAD

**Issue by knod** [codeforboston/clean-slate#79]
https://github.com/codeforboston/clean-slate/wiki/Contributing-to-App-Code

**Comment by srsexton94** [comment]
@jeremylang - compiled and formatted google doc with wiki information (still unfinished but closes this issue)
https://docs.google.com/document/d/1Up_4XqU7BPIQT6_ThCYJQeD63SpdhI0ZELyC01mgw3o/edit

See #77 
See #80  // unfinished
See #78 // unfinished
