### ISSUE TITLE
Does the PA dataset have the same crime rates as the FBI data?

### ISSUE THREAD

**Issue by mikemahoney218** [codeforboston/clean-slate#8]
PA was selected for this analysis because (a) they have more open privacy laws and (b) in an FBI dataset, PA had the most similar rates of crime as MA.

We need to validate that (b) remains true within our detailed dataset! As we don't have access to a detailed dataset for MA (or else we'd use it instead), instead we have to make sure the detailed dataset is close to the FBI summarized data.

This is a child issue of https://github.com/codeforboston/clean-slate/issues/6

**Comment by mikemahoney218** [comment]
A task dependent upon this one: If they are not, can we downsample such that they are representative?

**Comment by jeremylang** [comment]
No longer need a proxy state now that MA data is available.
