### ISSUE TITLE
Move app tool/stakeholders brainstorming page from wiki to google drive and

### ISSUE THREAD

**Issue by knod** [codeforboston/clean-slate#80]
also update it. It might not be relevant anymore, so we may just archive it.

https://github.com/codeforboston/clean-slate/wiki/Users:-Partners

**Comment by srsexton94** [comment]
Added to Documentation googledoc
https://docs.google.com/document/d/1Up_4XqU7BPIQT6_ThCYJQeD63SpdhI0ZELyC01mgw3o/edit#
