### ISSUE TITLE
Add doc with links to plectica and other UX wireframes

### ISSUE THREAD

**Issue by knod** [codeforboston/clean-slate#81]
In the google drive. What folder?

**Comment by niharikasingh** [comment]
See https://docs.google.com/document/d/1AbnF4-A0HP8LtzN7pTNjBEbC7DI--BTfSSIzEdg3U6g/edit

**Comment by knod** [comment]
Just fyi, I'm not sure this is the right place for all these things. The expungement plain eligibility flow logic is for the data team too, as they need to decide how to analyze eligibility in their data research. The sealing form UX flow, though, is just for the app team. What approach can we take?

**Comment by knod** [comment]
Once we figure that out, we can change the titles of the docs to be more appropriate.
