### ISSUE TITLE
Make a digital version of our technology comfort survey

### ISSUE THREAD

**Issue by knod** [codeforboston/clean-slate#82]
This survey: https://docs.google.com/document/d/1N164VBSRMXqUgOHSou6xrqPAgyHK7hhNPAwDzLrMOyA/edit

Save it in this folder: https://drive.google.com/drive/folders/1IlrR-KN5kf5qHGzajKOO3c6y3XSQ-16c?usp=sharing

**Google forms should not be our go-to for information gathering.** We have to resort to it right now, but we need to set up a better way so we're not in this position in the future.

**Comment by caitlincoffey** [comment]
Draft of form is here: https://docs.google.com/forms/d/1c5fc9NovQn27IWdwbNAVCe9DZ3o3M_-JTSN18r9fjIw/edit (need to add contact information, but other than that it is good)
