### ISSUE TITLE
Wiki link broken

### ISSUE THREAD

**Issue by knod** [codeforboston/clean-slate#88]
On https://github.com/codeforboston/clean-slate/wiki/Additional-Resources, the link to the Illinois page is broken: http://www.expunge.io/. The site doesn't exist anymore.

Just comment it out so we can look into it later.

**Comment by knod** [comment]
Well, it doesn't exist right now when this is being written.

**Comment by caitlincoffey** [comment]
New link: https://github.com/smartchicago/expunge.io . Project seems to be inactive. (Files haven't been updated in 4 years). Should we contact them?

**Comment by knod** [comment]
Good question. For the record: I think the group consensus was that this isn't a high priority right now.
