### ISSUE TITLE
Does the PA detailed dataset have a similar age distribution to MA?

### ISSUE THREAD

**Issue by mikemahoney218** [codeforboston/clean-slate#9]
We need to prove that our PA dataset is representative of MA crimes. To do so, we want to examine as many axes as possible to ensure our dataset is representative.

To that end, we want to know if our PA datasets age distribution resembles that of MA. In particular, we want to ensure that we have the same rates for under 21 offenders.

This is a child issue of https://github.com/codeforboston/clean-slate/issues/6

**Comment by jeremylang** [comment]
No longer need a proxy state now that MA data is available.
