### ISSUE TITLE
Reconsider usage of New Member Questions documents

### ISSUE THREAD

**Issue by niharikasingh** [codeforboston/clean-slate#90]
We have a couple of (https://docs.google.com/document/d/1mPlJSgK3c8mgHmDKKZPr-jpF2gWF_Y8uygG4LSjbJng/edit, https://docs.google.com/document/d/1WJGJijM3Fts1RtnKGQSn0tZ82TL4nqU9VRAhhkXyi4Q/edit#heading=h.ex3okxri3te8) documents that new members can write down their questions in. In late March (about one month later), we should reconsider whether onboarding members actually use these documents, or whether we should replace them with something else.

**Comment by knod** [comment]
Thoughts from meeting:
1. We haven't had new members for a while.
1. When we did have new members, not many of them wrote questions in those docs.
1. Some people did write questions, though, and we're not sure if people were really given the links to those docs.
1. We might have different places that are useful in different ways (but of those two docs we need to pick one)
   1. One of those docs for data/general questions
   1. App onboarding docs for one-on-one in-depth input about those docs
   1. App questionnaire fields asking for feedback for opportunity for quick capture.

**Comment by knod** [comment]
1. I think we picked the doc for 4.i.
1. I think each onboarding doc might itself might contain its in-depth feedback (4.ii).
1. 4.iii is already being taken care of in the questionnaire.

This might be done, but I'd like a memory check.

**Comment by niharikasingh** [comment]
Sounds right to me! I'm closing because of above.
