### ISSUE TITLE
Follow up on CfJJ possible new incoming data

### ISSUE THREAD

**Issue by knod** [codeforboston/clean-slate#96]
They may soon be getting good data for three counties. Stuff that shows if someone's committed multiple crimes, crimes that are eligible/ineligible, etc.

It might be a little while (forgot to ask how long), but let's remember to follow up on it.

**Comment by jeremylang** [comment]
This data has been received from CfJJ. Raw data was removed as it still had identifying information in it. Processed data can be found here: https://github.com/codeforboston/clean-slate/tree/master/data/processed
