### ISSUE TITLE
DECISION: *do not* Merge app project board with the main project board

### ISSUE THREAD

**Issue by knod** [codeforboston/clean-slate#98]
# Why

We're concerned we won't remember to check all the boards for all the issues (I think?)

# How

# Resources

# Proposal History

## 2020/03/03
1. Proposal issue made with 'proposal' label and other relevant labels. Was posted to Slack (with end date, voting chart, and link to this issue), and post was pinned to the channel.

**Comment by knod** [comment]
A few weeks ago we talked about whether to have three project boards or just one and we said three separate boards. Last week we described putting app items on the main board. I’m unclear on what part of the plan is changing and in what ways. Are we proposing we meld the app and main board? Does the app board still need to exist? Is there a different separation of concerns that I haven’t grasped? Etc.

**Comment by berit** [comment]
I was thinking of agenda items specifically since app tends to dominate the agenda anyway, but maybe it would be better to be judicious about keeping agenda items on their respective boards and help make the whole group portion of the meeting short.

**Comment by berit** [comment]
We decided to keep the boards separate. App-specific agenda items should be on the app board

**Comment by knod** [comment]
Three 5's - @berit , @knod , @niharikasingh

**Comment by ExperimentsInHonesty** [comment]
This issue is a good example of a small decision.  I am leaving this note, to help inform people who find this issue as an example of the Fist-to-Five process mentioned in the BOP Processes and Practices.
